docling_ingestion:
  input_dir: "data/runtime/02-pdfs/active"
  output_dir: "data/runtime/03-pdf_processing"

heuristics:
  full_dir: "data/runtime/03-pdf_processing"
  final_dir: "data/runtime/03-pdf_processing"
